const days=[['2026-07-18','Saturday','18'],['2026-07-19','Sunday','19'],['2026-07-20','Monday','20'],['2026-07-21','Tuesday','21'],['2026-07-22','Wednesday','22'],['2026-07-23','Thursday','23']];
const periods=[['morning','Morning','Breakfast'],['afternoon','Afternoon','Lunch'],['evening','Evening','Dinner']];
const blank=()=>Object.fromEntries(days.map(([key])=>[key,Object.fromEntries(periods.map(([p])=>[p,{meal:'',items:[]}]))]));
let schedule=blank(),active=0,view='day',saveTimer,status='Loading…';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function load(){try{const r=await fetch('/api/schedule',{cache:'no-store'});const d=await r.json();if(d.schedule)schedule=d.schedule;status='✓ Shared plan saved'}catch{status='Offline'}render()}
function queueSave(){status='Saving…';renderStatus();clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{const r=await fetch('/api/schedule',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({schedule})});if(!r.ok)throw 0;status='✓ Shared plan saved'}catch{status='Save failed'}renderStatus()},500)}
function renderStatus(){const e=document.querySelector('.save-status');if(e)e.textContent=status}
function setMeal(day,p,value){schedule[day][p].meal=value;queueSave()}
function setItem(day,p,i,value){schedule[day][p].items[i]=value;queueSave()}
function addItem(day,p){schedule[day][p].items.push('');render();document.querySelector(`[data-new="${p}"]`)?.focus();queueSave()}
function removeItem(day,p,i){schedule[day][p].items.splice(i,1);render();queueSave()}
function dayView(){const [key,name,date]=days[active];return `<section class="day-nav"><button ${active===0?'disabled':''} data-prev>←</button><div><strong>${name} ${date} July</strong><small>${active+1} of 6</small></div><button ${active===5?'disabled':''} data-next>→</button></section><div class="date-tabs">${days.map((d,i)=>`<button class="${i===active?'active':''}" data-day="${i}">${d[1].slice(0,3)}<b>${d[2]}</b></button>`).join('')}</div><main class="day-grid">${periods.map(([p,title,meal])=>{const s=schedule[key][p];return `<section class="period ${p}"><h2>${title}</h2><div class="box"><label>${meal}</label><textarea rows="2" data-meal="${p}" placeholder="${meal} at… or what are we cooking?">${esc(s.meal)}</textarea><div class="notes-title">Plans & reminders</div>${s.items.map((item,i)=>`<div class="note"><textarea rows="2" data-item="${p}:${i}" ${i===s.items.length-1&&item===''?`data-new="${p}"`:''} placeholder="Appointment, shopping, place to be…">${esc(item)}</textarea><button data-remove="${p}:${i}">×</button></div>`).join('')}<button class="add" data-add="${p}">+ Add entry</button></div></section>`}).join('')}</main>`}
function overview(){const filled=days.reduce((n,[key])=>n+periods.filter(([p])=>schedule[key][p].meal.trim()||schedule[key][p].items.some(Boolean)).length,0);return `<main class="overview"><div class="overview-head"><div><small>SIX-DAY AVAILABILITY</small><h2>Find an open block</h2><p><i class="planned"></i> Planned <i class="open"></i> Open</p></div><strong>${18-filled}<span>open blocks</span></strong></div><div class="overview-list">${days.map(([key,name,date],i)=>`<button class="day-row" data-open-day="${i}"><div class="day-name">${name}<small>${date} Jul</small></div><div class="slots">${periods.map(([p,title])=>{const s=schedule[key][p],has=s.meal.trim()||s.items.some(Boolean);return `<div class="slot ${has?'has':'blank'}"><b>${title}</b><span>${esc(s.meal||s.items.find(Boolean)||(has?'Planned':'OPEN'))}</span></div>`}).join('')}</div></button>`).join('')}</div></main>`}
function render(){document.querySelector('#app').innerHTML=`<header><div class="brand"><span>BJ</span><div><h1>Bill’s & Jeff’s Scheduler</h1><small>18–23 July 2026</small></div></div><div class="save-status">${status}</div><nav><button class="${view==='day'?'active':''}" data-view="day">Day</button><button class="${view==='overview'?'active':''}" data-view="overview">Overview</button></nav></header>${view==='day'?dayView():overview()}`;bind()}
function bind(){document.querySelectorAll('[data-view]').forEach(e=>e.onclick=()=>{view=e.dataset.view;render()});document.querySelector('[data-prev]')?.addEventListener('click',()=>{active--;render()});document.querySelector('[data-next]')?.addEventListener('click',()=>{active++;render()});document.querySelectorAll('[data-day]').forEach(e=>e.onclick=()=>{active=+e.dataset.day;render()});document.querySelectorAll('[data-open-day]').forEach(e=>e.onclick=()=>{active=+e.dataset.openDay;view='day';render()});const key=days[active][0];document.querySelectorAll('[data-meal]').forEach(e=>e.oninput=()=>setMeal(key,e.dataset.meal,e.value));document.querySelectorAll('[data-item]').forEach(e=>e.oninput=()=>{const[p,i]=e.dataset.item.split(':');setItem(key,p,+i,e.value)});document.querySelectorAll('[data-add]').forEach(e=>e.onclick=()=>addItem(key,e.dataset.add));document.querySelectorAll('[data-remove]').forEach(e=>e.onclick=()=>{const[p,i]=e.dataset.remove.split(':');removeItem(key,p,+i)})}
load();
